FROM node:latest

WORKDIR /app/front_server

COPY . /app/front_server/

RUN npm install

CMD ["npm", "run", "dev"]

######dumb-init 사용시

# FROM node:latest

# WORKDIR /app/front_server

# COPY . /app/front_server/

# RUN apt install -y dumb-init
# RUN npm install

# CMD ["/usr/bin/dumb-init", "--", "npm", "run", "dev"]